# Generated by Django 4.2.2 on 2023-06-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, null=True)),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('apellido', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
